apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: s3oig6dzu-go 
  janus-idp.io/tekton: s3oig6dzu-go
  backstage.io/kubernetes-id: s3oig6dzu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: s3oig6dzu-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  